### ISSUE TITLE
PropertyInspector class does not accept inActionInfo parameter

### ISSUE THREAD

**Issue by clamburger** [rweich/streamdeck-ts#14]
AbstractStreamdeckConnector's connectElgatoStreamDeckSocket method accepts four parameters:

```
private connectElgatoStreamDeckSocket(
    inPort: string,
    inPluginUUID: string,
    inRegisterEvent: string,
    inInfo: string,
): void
```

This is correct for the Plugin class, but the PropertyInspector receives an additional fifth parameter when instantiated ([inActionInfo](https://developer.elgato.com/documentation/stream-deck/sdk/property-inspector/#registration)). The connector does not currently accept this parameter, and without it, there's no way for the PropertyInspector to know what action it belongs to.

**Comment by rweich** [comment]
Hey, thanks for reporting!
should be available now (with 3.1.0 - as `actionInfo` property in the PI). hope it helps.

never really needed that, as (i think) you usually get the info in the events. so just out of curiosity: what do you use it for?

**Comment by clamburger** [comment]
Thanks for the quick update. I went back and checked and realised that `actionInfo` contains essentially the same fields as the `DidReceiveSettingsEvent`, so there was in fact a way for the PropertyInspector to know the action. Apologies for the confusion.

**Comment by rweich** [comment]
no worries. glad it works
